AWSTemplateFormatVersion: "2010-09-09"
Description: VPC Resources

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      InstanceTenancy: default
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"

  Igw:
    Type: AWS::EC2::InternetGateway
    Properties: {  }

  GatewayAttachIgw:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref Igw

  DhcpOption:
    Type: AWS::EC2::DHCPOptions
    Properties:
      DomainName: "ec2.internal"
      DomainNameServers:
        - AmazonProvidedDNS

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref PublicRouteTable
      GatewayId: !Ref Igw
    DependsOn: GatewayAttachIgw

  PublicSubnetAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref Vpc

  PublicInSubnetAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PublicSubnetAcl
      RuleNumber: "32000"
      Protocol: "-1"
      RuleAction: allow
      Egress: "false"
      CidrBlock: 0.0.0.0/0
      Icmp:
        Code: "-1"
        Type: "-1"
      PortRange:
        From: "1"
        To: "65535"

  PublicOutSubnetAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PublicSubnetAcl
      RuleNumber: "32000"
      Protocol: "-1"
      RuleAction: allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
      Icmp:
        Code: "-1"
        Type: "-1"
      PortRange:
        From: "1"
        To: "65535"

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc

  PrivateSubnetAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref Vpc

  PrivateInSubnetAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PrivateSubnetAcl
      RuleNumber: "32000"
      Protocol: "-1"
      RuleAction: allow
      Egress: "false"
      CidrBlock: 0.0.0.0/0
      Icmp:
        Code: "-1"
        Type: "-1"
      PortRange:
        From: "1"
        To: "65535"

  PrivateOutSubnetAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PrivateSubnetAcl
      RuleNumber: "32000"
      Protocol: "-1"
      RuleAction: allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
      Icmp:
        Code: "-1"
        Type: "-1"
      PortRange:
        From: "1"
        To: "65535"

  Zone1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: zone.yml
      Parameters:
        Range: 1
        Vpc: !Ref Vpc
        PublicNetworkAclId: !Ref PublicSubnetAcl
        PublicRouteTableId: !Ref PublicRouteTable
        PrivateNetworkAclId: !Ref PrivateSubnetAcl
        PrivateRouteTableId: !Ref PrivateRouteTable
        AvailabilityZone:
          Fn::Select:
            - 0
            - Fn::GetAZs: ""

  Zone2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: zone.yml
      Parameters:
        Range: 2
        Vpc: !Ref Vpc
        PublicNetworkAclId: !Ref PublicSubnetAcl
        PublicRouteTableId: !Ref PublicRouteTable
        PrivateNetworkAclId: !Ref PrivateSubnetAcl
        PrivateRouteTableId: !Ref PrivateRouteTable
        AvailabilityZone:
          Fn::Select:
            - 1
            - Fn::GetAZs: ""
  Zone3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: zone.yml
      Parameters:
        Range: 3
        Vpc: !Ref Vpc
        PublicNetworkAclId: !Ref PublicSubnetAcl
        PublicRouteTableId: !Ref PublicRouteTable
        PrivateNetworkAclId: !Ref PrivateSubnetAcl
        PrivateRouteTableId: !Ref PrivateRouteTable
        AvailabilityZone:
          Fn::Select:
            - 2
            - Fn::GetAZs: ""

  Zone4:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: zone.yml
      Parameters:
        Range: 4
        Vpc: !Ref Vpc
        PublicNetworkAclId: !Ref PublicSubnetAcl
        PublicRouteTableId: !Ref PublicRouteTable
        PrivateNetworkAclId: !Ref PrivateSubnetAcl
        PrivateRouteTableId: !Ref PrivateRouteTable
        AvailabilityZone:
          Fn::Select:
            - 3
            - Fn::GetAZs: ""
  Zone5:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: zone.yml
      Parameters:
        Range: 5
        Vpc: !Ref Vpc
        PublicNetworkAclId: !Ref PublicSubnetAcl
        PublicRouteTableId: !Ref PublicRouteTable
        PrivateNetworkAclId: !Ref PrivateSubnetAcl
        PrivateRouteTableId: !Ref PrivateRouteTable
        AvailabilityZone:
          Fn::Select:
            - 4
            - Fn::GetAZs: ""

  Zone6:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: zone.yml
      Parameters:
        Range: 6
        Vpc: !Ref Vpc
        PublicNetworkAclId: !Ref PublicSubnetAcl
        PublicRouteTableId: !Ref PublicRouteTable
        PrivateNetworkAclId: !Ref PrivateSubnetAcl
        PrivateRouteTableId: !Ref PrivateRouteTable
        AvailabilityZone:
          Fn::Select:
            - 5
            - Fn::GetAZs: ""

Outputs:
  Vpc:
    Description: VPC
    Value: !Ref Vpc

  AvailabilityZones:
    Description: "Availability zones actually used"
    Value: !Join [ ", ", [
      !GetAtt Zone1.Outputs.AvailabilityZone,
      !GetAtt Zone2.Outputs.AvailabilityZone,
      !GetAtt Zone3.Outputs.AvailabilityZone,
      !GetAtt Zone4.Outputs.AvailabilityZone,
      !GetAtt Zone5.Outputs.AvailabilityZone,
      !GetAtt Zone6.Outputs.AvailabilityZone,
    ] ]

  PublicSubnets:
    Description: Public Subnets
    Value: !Join [ ", ", [
        !GetAtt Zone1.Outputs.PublicSubnet,
        !GetAtt Zone2.Outputs.PublicSubnet,
        !GetAtt Zone3.Outputs.PublicSubnet,
        !GetAtt Zone4.Outputs.PublicSubnet,
        !GetAtt Zone5.Outputs.PublicSubnet,
        !GetAtt Zone6.Outputs.PublicSubnet,
    ] ]

  PublicSubnet1:
    Description: Public Subnet 1
    Value: !GetAtt Zone1.Outputs.PublicSubnet
  PublicSubnet2:
    Description: Public Subnet 2
    Value: !GetAtt Zone2.Outputs.PublicSubnet
  PublicSubnet3:
    Description: Public Subnet 3
    Value: !GetAtt Zone3.Outputs.PublicSubnet
  PublicSubnet4:
    Description: Public Subnet 4
    Value: !GetAtt Zone4.Outputs.PublicSubnet
  PublicSubnet5:
    Description: Public Subnet 5
    Value: !GetAtt Zone5.Outputs.PublicSubnet
  PublicSubnet6:
    Description: Public Subnet 6
    Value: !GetAtt Zone6.Outputs.PublicSubnet
