AWSTemplateFormatVersion: '2010-09-09'
Description: coda infra
Parameters:
  BastionAmiId:
    Type: String
  KeyName:
    Type: String
  BucketInfra:
    Description: Infrastructure bucket
    Type: String
  CodaAmiId:
    Description: AMI id for Coda server.
    Type: AWS::EC2::Image::Id
  CodaInstanceType:
    Description: Coda EC2 instance type.
    ConstraintDescription: must be a valid EC2 instance type.
    Type: String
    AllowedValues:
    - c5.2xlarge
    Default: c5.2xlarge
  CodaWorkerAmiId:
    Description: AMI id for Coda server.
    Type: AWS::EC2::Image::Id
  CodaWorkerMinSize:
    Description: The Min Size for the Coda worker AutoScale group.
    Type: Number
    Default: 1
  CodaWorkerMaxSize:
    Description: The Max Size for the Coda worker AutoScale group.
    Type: Number
    Default: 1
Resources:
  CodaRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /application/
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/init-stack-templatebucket-h0zgfseupync/cee0746d5ee032b627e0e272353edb76.template
      TimeoutInMinutes: 60
  BastionStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - VpcStack
    Properties:
      TemplateURL: https://s3.amazonaws.com/init-stack-templatebucket-h0zgfseupync/64ef5ee32df432b1ae51d57f476b963e.template
      TimeoutInMinutes: 30
      Parameters:
        Vpc:
          Fn::GetAtt:
          - VpcStack
          - Outputs.Vpc
        Subnet:
          Fn::GetAtt:
          - VpcStack
          - Outputs.PublicSubnet1
        KeyName:
          Ref: KeyName
        AmiId:
          Ref: BastionAmiId
        SecurityGroups:
        - Ref: AWS::NoValue
  CodaWorkerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - BastionStack
    - VpcStack
    Properties:
      TemplateURL: https://s3.amazonaws.com/init-stack-templatebucket-h0zgfseupync/9e61e6c3b8d23ed2dc37a2f4431f4d5d.template
      TimeoutInMinutes: 30
      Parameters:
        VpcId:
          Fn::GetAtt:
          - VpcStack
          - Outputs.Vpc
        CodaAmiId:
          Ref: CodaWorkerAmiId
        CodaRole:
          Ref: CodaRole
        KeyName:
          Ref: KeyName
        MinSize:
          Ref: CodaWorkerMinSize
        MaxSize:
          Ref: CodaWorkerMaxSize
        InstanceType:
          Ref: CodaInstanceType
        SecurityGroups:
        - Fn::GetAtt:
          - BastionStack
          - Outputs.ClientSecurityGroup
        Subnets:
          Fn::GetAtt:
          - VpcStack
          - Outputs.PublicSubnets
        AvailabilityZones:
          Fn::GetAtt:
          - VpcStack
          - Outputs.AvailabilityZones
